spring:
  datasource:
    url: jdbc:mysql://47.115.208.86:3306/medical
    username: root
    password: 2577cs242220
    driver-class-name: com.mysql.cj.jdbc.Driver
chen:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5[chen]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token